### PR TITLE
Fix API URL. Fixes #10

### LINKED ISSUE #10: Not getting data / Login Error
Hello!

i've seen several errors in the log today:

`"error" from custom_components/pajgps/device_tracker.py:333`
and
`"No data for PAJ GPS device XXXXXXX" from custom_components/pajgps/device_tracker.py:292`

The app didn't work either but the website did just fine so I waved it off.

Suddenly the finder app gave me message about a new security concept implemented by PAJ resulting in the need for changing my password. The login in the app and portal seems to work just fine now but additionally to the previous errors I now get

`"Could not get login token" from custom_components/pajgps/device_tracker.py:435`

after reconfiguring the integration.

So I guess they changed something in the API or authentification methods. Still hoping this is just temporary but just in case...

Thanks!

### PR DESCRIPTION
**Pull request by iursevla**
* To fix #10 (Seems like the URL needs to be `https://connect.paj-gps.de/api/v1/`
* Added extra debug logging. Can be enabled in `configuration.yaml`
```yaml
logger:
  default: error 
  logs:
    custom_components.pajgps.device_tracker: debug
```

image

### CODE REVIEW

**Comment by Skipperro** [comment]
Looking good, but please give me few days to test it and maybe contact PAJ GPS, because it is working fine with old URL for all my devices, so I want to make sure this change won't brake anything.

**Comment by iursevla** [comment]
@Skipperro Thanks.

Meanwhile, I updated the code locally with this change

**Comment by shering1988** [comment]
> @Skipperro Thanks.
> 
> Meanwhile, I updated the code locally with this change

i also did and can confirm that the "v1" url does the trick and the integration is working fine again.

**Comment by Skipperro** [comment]
Working well also on older devices. It will be part of next release (0.4.0)
Thanks @iursevla

**Pull request merged**
